# Generated by Django 5.1.1 on 2025-03-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type_name', models.CharField(max_length=30)),
                ('add_info', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_full_name', models.CharField(max_length=150)),
                ('organization_short_name', models.CharField(max_length=50)),
                ('inn', models.CharField(max_length=10)),
                ('kpp', models.CharField(max_length=9)),
                ('ogrn', models.CharField(max_length=13)),
                ('responsible_person_surname', models.CharField(max_length=50)),
                ('responsible_person_name', models.CharField(max_length=50)),
                ('responsible_person_patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('responsible_person_email', models.CharField(max_length=50)),
                ('responsible_person_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=10)),
                ('add_info', models.CharField(blank=True, max_length=250, null=True)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.addresstype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
