# Generated by Django 5.1.1 on 2025-03-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator_specialist_surname', models.CharField(max_length=50)),
                ('aggregator_specialist_name', models.CharField(max_length=50)),
                ('aggregator_specialist_patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('aggregator_specialists_department', models.CharField(max_length=30)),
                ('aggregator_specialists_position', models.CharField(max_length=20)),
                ('aggregator_specialists_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('add_info', models.CharField(blank=True, max_length=250, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatorSpecialistConnectorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aggregator.aggregatorspecialist')),
                ('connection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aggregator.connectionrequest')),
            ],
        ),
    ]
