# Generated by Django 5.1.1 on 2025-03-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatorspecialist',
            name='aggregator_specialist_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='aggregatorspecialist',
            name='aggregator_specialist_patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='aggregatorspecialist',
            name='aggregator_specialist_surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='aggregatorspecialist',
            name='aggregator_specialists_department',
            field=models.CharField(max_length=30, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='aggregatorspecialist',
            name='aggregator_specialists_phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='aggregatorspecialist',
            name='aggregator_specialists_position',
            field=models.CharField(max_length=20, verbose_name='Должность'),
        ),
    ]
