# Generated by Django 5.1.1 on 2025-03-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_detail_code', models.CharField(max_length=3)),
                ('service_detail_name', models.CharField(max_length=50)),
                ('service_detail_cost', models.IntegerField()),
                ('service_detail_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=2)),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateTimeField()),
                ('add_info', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.servicedetail')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.servicerequest')),
            ],
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='type_of_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.typeofservice'),
        ),
    ]
