# Generated by Django 5.1.1 on 2025-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_surname', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
