# Generated by Django 5.1.1 on 2025-02-19 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type_name', models.CharField(max_length=30)),
                ('add_info', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatorSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator_specialist_surname', models.CharField(max_length=50)),
                ('aggregator_specialist_name', models.CharField(max_length=50)),
                ('aggregator_specialist_patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('aggregator_specialists_department', models.CharField(max_length=30)),
                ('aggregator_specialists_position', models.CharField(max_length=20)),
                ('aggregator_specialists_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('add_info', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_surname', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_full_name', models.CharField(max_length=150)),
                ('organization_short_name', models.CharField(max_length=50)),
                ('inn', models.CharField(max_length=10)),
                ('kpp', models.CharField(max_length=9)),
                ('ogrn', models.CharField(max_length=13)),
                ('responsible_person_surname', models.CharField(max_length=50)),
                ('responsible_person_name', models.CharField(max_length=50)),
                ('responsible_person_patronymic', models.CharField(blank=True, max_length=50, null=True)),
                ('responsible_person_email', models.CharField(max_length=50)),
                ('responsible_person_phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_detail_code', models.CharField(max_length=3)),
                ('service_detail_name', models.CharField(max_length=50)),
                ('service_detail_cost', models.IntegerField()),
                ('service_detail_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=2)),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AggregatorSpecialistConnectorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregator_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aggregatorspecialist')),
                ('connection_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.connectionrequest')),
            ],
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=10)),
                ('add_info', models.CharField(blank=True, max_length=250, null=True)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.addresstype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_service', models.DateTimeField()),
                ('add_info', models.CharField(blank=True, max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicedetail')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servicerequest')),
            ],
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='type_of_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typeofservice'),
        ),
    ]
